service: serverless-provisioned-concurrency
frameworkVersion: "^3"

params:
  default:
    defaultResourceName: ${self:service}-${self:provider.stage}

provider:
  name: aws
  stage: dev
  region: sa-east-1
  runtime: nodejs18.x
  architecture: arm64
  timeout: 10
  memorySize: 256
  logRetentionInDays: 1
  apiGateway:
    shouldStartNameWithService: true
  environment:
    MONGODB_URI: ${ssm:${param:defaultResourceName}-mongodb}
  iam:
    role:
      name: ${param:defaultResourceName}-lambda-role
  vpc:
    securityGroupIds:
      - ${ssm:${param:defaultResourceName}-securityGroupId}
    subnetIds:
      - ${ssm:${param:defaultResourceName}-subnetId-1a}
      - ${ssm:${param:defaultResourceName}-subnetId-1b}
      - ${ssm:${param:defaultResourceName}-subnetId-1c}

layers:
  layerCommon:
    path: layers/layerCommon
    name: ${param:defaultResourceName}-layer-common

package:
  patterns:
    - "!node_modules/**"
    - "!package-lock.json"
    - "!package.json"
    - "!layers/**"

functions:
  listCoursesProvisioned:
    handler: serverless/functions/Course/listCourses.handler
    provisionedConcurrency: 5
    layers:
      - { Ref: LayerCommonLambdaLayer }
    events:
      - http:
          path: /courses/with-provisioned-concurrency
          method: get
          cors: true

  listCoursesNoProvisioned:
    handler: serverless/functions/Course/listCourses.handler
    layers:
      - { Ref: LayerCommonLambdaLayer }
    events:
      - http:
          path: /courses/without-provisioned-concurrency
          method: get
          cors: true
